services:

  neo4j5:
    image: neo4j:5.19.0
    container_name: neo4j5
    volumes:
     - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j5/data:/data:rw
     - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j5/logs:/logs:rw
     - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j5/conf:/var/lib/neo4j/conf:rw
     - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j5/plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j123